version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://dummy:dummy@cluster0.4fkc0yt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge